expr: Train ODE-Net (MNIST)

device: &device cuda:0
parallel: false

data:
  dataset: MNIST
  root: data/
  download: True
  mode: train

model:
  name: ODENet

hyperparameters:
  batch_size: 32
  optim: AdamW
  lr: 0.0001
  loss_fn: cross-entropy
  epochs: 200

save:
  name: odenet_mnist
  weights_path: saved/weights
  loss_path: saved/loss